Repository deathworlders/online, pull requests merged in 2018-05, with the labels that each got.

#5 Create new book directory and index
  content/books/bolthole-aces/_index.md
Labels: collab

#6 - Add "Books" menu to navigate to content/books _index.md
  config.toml
  content/_index.md
  content/books/_index.md
  content/books/bolthole-aces/_index.md
  layouts/menu/listbooks.html
  layouts/partials/listdir.html
Labels: enhancement

#7 - Tidy up "Books" menu
  layouts/menu/listbooks.html
  layouts/partials/listdir.html
  static/css/menu.css
Labels: enhancement, good first issue

#57 Fix chapters 0-10
  content/books/deathworlders/chapter-00-kevin-jenkins-experience.md
  content/books/deathworlders/chapter-01-run-little-monster.md
  content/books/deathworlders/chapter-02-aftermath.md
  content/books/deathworlders/chapter-03-eventful-month.md
  content/books/deathworlders/chapter-04-quarantine.md
  content/books/deathworlders/chapter-05-deliverance.md
  content/books/deathworlders/chapter-05.5-interlude-ultimatum.md
  content/books/deathworlders/chapter-06-taking-back-sky.md
  content/books/deathworlders/chapter-06.5-interlude-jargon.md
  content/books/deathworlders/chapter-07-tensions.md
  content/books/deathworlders/chapter-08-alternatives.md
  content/books/deathworlders/chapter-09-gains-losses.md
  content/books/deathworlders/chapter-10-legwork.md
Labels: bug

#59 Fixes pr #58, fixes #20, #21, #22, #23
  content/books/deathworlders/chapter-10-legwork.md
  content/books/deathworlders/chapter-11-direct-delivery.md
  content/books/deathworlders/chapter-12-only-human.md
  content/books/deathworlders/chapter-13-tall-tales.md
Labels: bug, enhancement

#61 Chapter 14-16
  content/books/deathworlders/chapter-14-hornets-nest.md
  content/books/deathworlders/chapter-15-forever-changed.md
  content/books/deathworlders/chapter-16-firebird.md
Labels: bug, work needed

#62 Fix chapters 17-20
  content/books/deathworlders/chapter-12-only-human.md
  content/books/deathworlders/chapter-16-firebird.md
  content/books/deathworlders/chapter-17-battles.md
  content/books/deathworlders/chapter-18-baggage.md
  content/books/deathworlders/chapter-19-baptisms.md
  content/books/deathworlders/chapter-20-exorcisms.md
Labels: bug
