Repository deathworlders/online, pull requests merged in 2019-01, with the labels that each got.

#97 Basic formatting mass-fix
  content/books/deathworlders/chapter-01-run-little-monster.md
  content/books/deathworlders/chapter-05.5-interlude-ultimatum.md
  content/books/deathworlders/chapter-06-taking-back-sky.md
  content/books/deathworlders/chapter-07-tensions.md
  content/books/deathworlders/chapter-09-gains-losses.md
  content/books/deathworlders/chapter-10-legwork.md
  content/books/deathworlders/chapter-12-only-human.md
  content/books/deathworlders/chapter-13-tall-tales.md
  content/books/deathworlders/chapter-14-hornets-nest.md
  content/books/deathworlders/chapter-15-forever-changed.md
  content/books/deathworlders/chapter-16-firebird.md
  content/books/deathworlders/chapter-18-baggage.md
  content/books/deathworlders/chapter-20-exorcisms.md
  content/books/deathworlders/chapter-21-dragon-dreams.md
  content/books/deathworlders/chapter-22-warhorse-pt1-first-year.md
  content/books/deathworlders/chapter-22-warhorse-pt2-second-year.md
  content/books/deathworlders/chapter-22-warhorse-pt3-third-year.md
  content/books/deathworlders/chapter-22-warhorse-pt4-fourth-year.md
  content/books/deathworlders/chapter-22-warhorse-pt5-fifth-year.md
  content/books/deathworlders/chapter-22-warhorse-pt6-operation-nova-hound.md
  content/books/deathworlders/chapter-24-alien-world.md
  content/books/deathworlders/chapter-25-where-we-stand.md
  content/books/deathworlders/chapter-26-blood-ash.md
  content/books/deathworlders/chapter-27-playing-fire.md
  content/books/deathworlders/chapter-28-misfits.md
Labels: bug

#98 Formatting Fix Pt II
  content/books/deathworlders/chapter-27-playing-fire.md
  content/books/deathworlders/chapter-29-forges.md
  content/books/deathworlders/chapter-30-hearts-minds.md
  content/books/deathworlders/chapter-31-touching-down.md
  content/books/deathworlders/chapter-32-deep-wounds.md
Labels: bug

#94 Added epub button to supported stories
  content/books/bolthole-aces/_index.md
  content/books/deathworlders/_index.md
  content/books/good-training-champions-pt-i/_index.md
  content/books/good-training-champions-pt-ii/_index.md
  content/books/good-training/_index.md
  content/books/waters-babylon/_index.md
Labels: enhancement

#101 Fix ePub escape issues
  content/books/deathworlders/chapter-05.5-interlude-ultimatum.md
  content/books/deathworlders/chapter-06-taking-back-sky.md
  content/books/deathworlders/chapter-14-hornets-nest.md
  content/books/deathworlders/chapter-15-forever-changed.md
  content/books/deathworlders/chapter-26-blood-ash.md
  content/books/deathworlders/chapter-27-playing-fire.md
  content/books/deathworlders/chapter-29-forges.md
  content/books/deathworlders/chapter-31-touching-down.md
  content/books/deathworlders/chapter-34-states-mind.md
  content/books/deathworlders/chapter-35-event-horizions.md
  content/books/deathworlders/chapter-39-nirvana-cage.md
  content/books/deathworlders/chapter-40-war-two-worlds-pt1-instigation.md
  content/books/deathworlders/chapter-44-samsara.md
Labels: bug, enhancement
